version: '2'

volumes:
  pgdata:
    driver: local

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED=true
      - PYTHONDONTWRITEBYTECODE=true
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data
