# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('order',), 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-created_at',), 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('order',), 'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
